### ISSUE TITLE
HitScoreVisualizerのHITSCORE BLOOMをOFFにしたときに文字化けする

### ISSUE THREAD

**Issue by rynan4818** [denpadokei/CustomMenuMusic#18]
こちらの、[NowPlaying.cs](https://github.com/denpadokei/CustomMenuMusic/blob/master/CustomMenuMusic/NowPlaying.cs)を参考に、[PlayerInfoViewer](https://github.com/rynan4818/PlayerInfoViewer)を作成させてもらったのですが、下記のIssuesでHitScoreVisualizerで文字化けが発生する報告がありました。
https://github.com/rynan4818/PlayerInfoViewer/issues/1

原因はこの部分で、削除すると解消されます。
https://github.com/denpadokei/CustomMenuMusic/blob/master/CustomMenuMusic/NowPlaying.cs#L151
なぜ、HitScoreVisualizerに影響が出るのかは不明です。

表示をカーブさせるためにCurvedCanvasSettingsを使用するのに必要ですが、実際のところカーブさせなくても殆ど変わらないので
PlayerInfoViewerでは削除しました。

HitScoreVisualizer側の問題の様にも思いますが、一応ご連絡しておきます。

**Comment by denpadokei** [comment]
報告ありがとうございます。
コード見直したところ、よくわからんのでHitScoreVizualizerと同じフォントをつかうようにしました。

デフォルトのフォントなので取得してセットしなおす意味があるのかはわかりませんが。
